.. _system-requirements:

System Requirements
===================

.. rubric:: MicroEJ SDK and MicroEJ Studio

- **Intel x64 PC with minimum :**
   - Dual-core Core i5 processor
   - 4GB RAM
   - 4GB Disk for MicroEJ SDK
   - 1GB Disk for MicroEJ Studio
- **Operating Systems :**
   - Windows 10, Windows 8.1, Windows 8, Windows 7, Windows Vista or Windows XP SP3
   - Linux distributions (tested on Ubuntu 12.04 and Ubuntu 14.04)
   - Mac OS X (tested on version 10.10 Yosemite, 10.11 El Capitan, 10.14 Mojave)

..
   | Copyright 2008-2020, MicroEJ Corp. Content in this space is free 
   for read and redistribute. Except if otherwise stated, modification 
   is subject to MicroEJ Corp prior approval.
   | MicroEJ is a trademark of MicroEJ Corp. All other trademarks and 
   copyrights are the property of their respective owners.
