# Copyright 2025, MicroEJ Corp. Content in this space is free 
# for read and redistribute. Except if otherwise stated, modification is subject to MicroEJ Corp prior approval.
# MicroEJ is a trademark of MicroEJ Corp. All other trademarks and copyrights are the property of their respective owners.

[libraries]
# Core Engine
architecture =          { version = "8.5.0" }

# Other MicroEJ Libraries and APIs

# UI

# Other MicroEJ Foundation Libraries
