%% Copyright 2008-2023, MicroEJ Corp. Content in this space is free for read and redistribute. Except if otherwise stated, modification is subject to MicroEJ Corp prior approval.
%% MicroEJ is a trademark of MicroEJ Corp. All other trademarks and copyrights are the property of their respective owners.

graph LR 
    IDE(IDE/Debugger) --> |cmd jdwp| JDWP(Proxy JDWP/VEE Data) 
    JDWP --> |cmd reply jdwp| IDE
    JDWP -.-> |events jdwp| IDE
    JDWP --> |load file| ELF(VEE.out)
    JDWP --> |load file| Jars(VM and Soar models)
    JDWP --> |load file| MEMDUMP(VEE-Memory.dump)